# Pytorch nn Module


In [26]:
import torch
import torch.nn as nn

In [27]:
print(torch.__version__)

2.9.0+cu126


In [28]:
# pip install torchinfo

In [29]:
from torchinfo import summary

In [39]:
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()

        self.neural_network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.neural_network(features)

In [40]:
features = torch.rand(10,5)

In [41]:
features

tensor([[0.3363, 0.0466, 0.6001, 0.5824, 0.8844],
        [0.3733, 0.2814, 0.0857, 0.0200, 0.4780],
        [0.0577, 0.0503, 0.9961, 0.0266, 0.8794],
        [0.3202, 0.0663, 0.6624, 0.1480, 0.4021],
        [0.1488, 0.9975, 0.0281, 0.3237, 0.5970],
        [0.4250, 0.7787, 0.5522, 0.1088, 0.1942],
        [0.4305, 0.8902, 0.6165, 0.2380, 0.7076],
        [0.1694, 0.7775, 0.8894, 0.4948, 0.7112],
        [0.6262, 0.9584, 0.9712, 0.3890, 0.1680],
        [0.3667, 0.7602, 0.9090, 0.9881, 0.5477]])

In [42]:
model = Model(features.shape[1])

In [43]:
features.shape[1]

5

In [44]:
model(features)

tensor([[0.4408],
        [0.4394],
        [0.4438],
        [0.4438],
        [0.4438],
        [0.4438],
        [0.4438],
        [0.4438],
        [0.4438],
        [0.4438]], grad_fn=<SigmoidBackward0>)

In [49]:
# To get the weights of the FIRST linear layer (num_features -> 3)
print(model.neural_network[0].weight)

# To get the weights of the SECOND linear layer (3 -> 1)
print(model.neural_network[2].weight)

Parameter containing:
tensor([[ 0.0990, -0.2383, -0.3609,  0.1980,  0.0838],
        [-0.0585, -0.3248, -0.2611, -0.2212, -0.0340],
        [-0.2589,  0.1128, -0.3691, -0.3375, -0.3485]], requires_grad=True)
Parameter containing:
tensor([[-0.2299, -0.0994, -0.3233]], requires_grad=True)


In [51]:
# To get the bias of the FIRST linear layer (num_features -> 3)
print(model.neural_network[0].bias)

# To get the bias of the SECOND linear layer (3 -> 1)
print(model.neural_network[2].bias)

Parameter containing:
tensor([ 0.0575,  0.2432, -0.4057], requires_grad=True)
Parameter containing:
tensor([-0.2258], requires_grad=True)


In [52]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00